name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    env:
      CI: true
    steps:
      # Setup.
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn dist
      - run: yarn test

      # Coverage.
      - run: yarn coverage
      - run: yarn coverage:report
      - uses: codecov/codecov-action@v4
        with:
          files: coverage/coverage.lcov
